# Generated by Django 2.0.6 on 2018-07-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='user',
            new_name='users',
        ),
    ]
