# Generated by Django 2.0.6 on 2018-07-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_checker', '0002_auto_20180702_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='users',
            new_name='user',
        ),
    ]
