# Generated by Django 2.0.6 on 2018-07-02 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_checker', '0003_auto_20180702_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='user',
        ),
        migrations.AddField(
            model_name='buses',
            name='user',
            field=models.OneToOneField(default=45, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
