# Generated by Django 2.0.6 on 2018-07-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_checker', '0004_auto_20180702_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
